[features]
seeds = false
skip-lint = false
[programs.devnet]
spl_vault = "5N3f7WtQLAzYr1X49jkkjnLtLd7Y2yEijcXScCJsZ86F"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/work/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
